name: C
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - name: Download
      run: Invoke-WebRequest https://bin.equinox.io/c/4VmDzA7iaHb/ngrok-stable-windows-amd64.zip -OutFile ngrok.zip
    - name: Extract
      run: Expand-Archive ngrok.zip
    - name: Auth
      run: .\\ngrok\\ngrok.exe authtoken 2DU4J5Le9QZh9HMYA1tabCH2XYI_3Y3169B1XQzkz3pVerP9u
      env:
        NGROK_AUTH_TOKEN: $\{\{ secrets.NGROK_AUTH_TOKEN \}\}
    - name: Enable TS
      run: Set-ItemProperty -Path 'HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server'-name "fDenyTSConnections" -Value 0
    - run: Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
    - run: Set-ItemProperty -Path 'HKLM:\\System\\CurrentControlSet\\Control\\Terminal Server\\WinStations\\RDP-Tcp' -name "UserAuthentication" -Value 1
    - run: Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
    - run: Invoke-WebRequest https://raw.githubusercontent.com/Helpless69/test/main/resources/start.bat -OutFile start.bat
    - name: Creating Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'
    - name: Connect to RDP [Copy ip, username, password from here]
      run: cmd /c start.bat
    - name: Keep Workflow Active
      run: |
        echo "This step will keep the workflow active for 6 hours."
        sleep 21600 # Sleep for 1 hour, you can repeat this line to sleep for the desired duration.
